### ISSUE TITLE
Buffer get nil

### ISSUE THREAD

**Issue by drcode2** [rubrikinc/fluent-plugin-sentry#2]
I got buffer error, past my log:

g=nil, variables=nil>
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: dequeueing a chunk instance=70061799250760
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: chunk dequeued instance=70061799250760 metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: trying flush for a chunk chunk="5a253a68dee7936a0724c33583b38f05"
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: adding write count instance=70061798908380
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: executing sync write chunk="5a253a68dee7936a0724c33583b38f05"
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: write operation done, committing chunk="5a253a68dee7936a0724c33583b38f05"
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: committing write operation to a chunk chunk="5a253a68dee7936a0724c33583b38f05" delayed=false
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: purging a chunk instance=70061799250760 chunk_id="5a253a68dee7936a0724c33583b38f05" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: chunk purged instance=70061799250760 chunk_id="5a253a68dee7936a0724c33583b38f05" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: done to commit a chunk chunk="5a253a68dee7936a0724c33583b38f05"
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:24 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:25 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:25 +0300 [trace]: #0 fluent/log.rb:281:trace: writing events into buffer instance=70061799250760 metadata_size=1
fluentd_1  | 2020-04-02 22:17:25 +0300 [trace]: #0 fluent/log.rb:281:trace: enqueueing all chunks in buffer instance=70061799250760
fluentd_1  | 2020-04-02 22:17:25 +0300 [trace]: #0 fluent/log.rb:281:trace: enqueueing chunk instance=70061799250760 metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=nil, tag=nil, variables=nil>

**Comment by drcode2** [comment]
I fixed it 

It seems to be raven version,
I have replaced:
#spec.add_runtime_dependency "sentry-raven", "~> 2.7"
  spec.add_runtime_dependency "sentry-raven", "~> 0.15.0"

in file:
fluent-plugin-sentry.gemspec

Now its working

**Comment by rfitzhugh** [comment]
Glad it's working now, cheers!
